import Head from "next/head"
import Header from "../components/Header"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu Clone Build</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Building Hulu</h1>

      {/* Header */}
      <Header />

      {/* Navbar */}

      {/* Results */}
    </div>
  )
}
